# Change these first
owner: myqua
repo: LOUIS-upptime
user-agent: myqua

sites:
- name: BRCC Enterprise
  url: https://brcc.ent.sirsi.net/client/en_US/brcc/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: BPCC Enterprise
  url: https://bpcc.ent.sirsi.net/client/en_US/bpcc/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: Delta Enterprise
  url: https://delta.ent.sirsi.net/client/en_US/delta/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: Fletcher Enterprise
  url: https://fletcher.ent.sirsi.net/client/en_US/fletcher/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: Grambling Enterprise
  url: https://grambling.ent.sirsi.net/client/en_US/grambling/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: LSU Enterprise
  url: https://lsu.ent.sirsi.net/client/en_US/lsu/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: LSU-A Enterprise
  url: https://lsua.ent.sirsi.net/client/en_US/lsua/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: LSUCES Enterprise
  url: https://lsuces.ent.sirsi.net/client/en_US/lsuces/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: LSU-E Enterprise
  url: https://lsue.ent.sirsi.net/client/en_US/lsue/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: LSU Law Enterprise
  url: https://lsulaw.ent.sirsi.net/client/en_US/lsulaw/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: LSU-S Enterprise
  url: https://lsus.ent.sirsi.net/client/en_US/lsus/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: McNeese Enterprise
  url: https://mcneese.ent.sirsi.net/client/en_US/mcneese/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: Centenary Enterprise
  url: https://centenary.ent.sirsi.net/client/en_US/centenary/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: LaTech Enterprise
  url: https://latech.ent.sirsi.net/client/en_US/latech/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: Loyola New Orleans Enterprise
  url: https://loyno.ent.sirsi.net/client/en_US/loyola/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: LUMCON Enterprise
  url: https://lumcon.ent.sirsi.net/client/en_US/lumcon/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: Nicholls Enterprise
  url: https://nicholls.ent.sirsi.net/client/en_US/nicholls/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: Northshore Enterprise
  url: https://northshore.ent.sirsi.net/client/en_US/northshore/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: NSULA Enterprise
  url: https://nsula.ent.sirsi.net/client/en_US/nsula/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: Nunez Enterprise
  url: https://nunez.ent.sirsi.net/client/en_US/nunez/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: FranU Enterprise
  url: https://franu.ent.sirsi.net/client/en_US/franu/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: RPCC Enterprise
  url: https://rpcc.ent.sirsi.net/client/en_US/rpcc/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: SLCC Enterprise
  url: https://slcc.ent.sirsi.net/client/en_US/slcc/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: UHCNO Enterprise
  url: https://uhcno.ent.sirsi.net/client/en_US/uhcno/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: CLTCC Enterprise
  url: https://cltcc.ent.sirsi.net/client/en_US/cltcc/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: Delgado Enterprise
  url: https://delgado.ent.sirsi.net/client/en_US/delgado/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: Loyola Law Enterprise
  url: https://loynolaw.ent.sirsi.net/client/en_US/loynolaw/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: NOBTS Enterprise
  url: https://nobts.ent.sirsi.net/client/en_US/nobts/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: SLU Enterprise
  url: https://slu.ent.sirsi.net/client/en_US/slu/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: SOWELA Enterprise
  url: https://sowela.ent.sirsi.net/client/en_US/sowela/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: SUBR Enterprise
  url: https://subr.ent.sirsi.net/client/en_US/subr/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: SULAW Enterprise
  url: https://sulaw.ent.sirsi.net/client/en_US/sulaw/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: SUNO Enterprise
  url: https://suno.ent.sirsi.net/client/en_US/suno/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: SUSLA Enterprise
  url: https://susla.ent.sirsi.net/client/en_US/susla/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: ULL Enterprise
  url: https://ull.ent.sirsi.net/client/en_US/ull/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: ULM Enterprise
  url: https://ulm.ent.sirsi.net/client/en_US/ulm/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: UNO Enterprise
  url: https://uno.ent.sirsi.net/client/en_US/uno/search/results?te=
  __dangerous__body_degraded: "No Results"
- name: KWYJIBO Test
  url: https://lsuces.ent.sirsi.net/client/en_US/lsuces/search/results?qu=kwyjibo&te=SD_LSUCES
  __dangerous__body_degraded: "No results found"
  
assignees:
  - myqua

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /LOUIS-upptime
  logoUrl: https://s3.amazonaws.com/libapps/accounts/36809/images/tagline_logo_trans.png
  name: LOUIS Upptime
  introTitle: "This is a status page for checking LOUIS web applications, such as Enterprise instances."
  introMessage: Powered by Upptime.
  navbar:
    - title: LOUIS
      href: https://louislibraries.org
    - title: GitHub for this Upptime instance.
      href: https://github.com/$OWNER/$REPO
  theme: light
      
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
# Run checks every 20 minutes using cron syntax
  uptime: "*/15 * * * *"
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
